### ISSUE TITLE
Inaccurate notifications

### ISSUE THREAD

**Issue by Git-Forked** [theAkito/webmon#41] opened 2022-10-23 22:08 UTC
Using F-Droid version 2.8.0 of Webmon, 
on a Samsung Android 10 mobile phone.

I am experiencing inaccurate notifications which state that there was an issue with the website(s), but upon clicking the notification, the app itself shows no issues. This has been happening with previous versions as well. 

I found a reference that someone else has reported this issue, but the issue report is now marked as closed: 
https://github.com/theAkito/webmon/issues/3

Please consider looking into this issue again, if you would.  Thank you for your time.

**Comment by theAkito** [comment] 2022-10-23 22:42
Greetings 👋🏻

\
\
Does it happen only with specific websites & services?

Which configurations did you enable?

If it only happens for specific websites, then which website specific configurations did you apply?

If possible, could you share the websites this issue comes up with?

Does it always happen the same way or does it vary?

\
In my case, I have like 20 websites to be checked in the app and every single one shows the correct result. Many of them currently do not work, so I am also testing how failure detection works and it works really well.

Which is why I really need more information on your issue, to be able to reproduce it, as I do not experience it with the data I have.

\
\
Thank you for your time. 🙂

**Comment by Git-Forked** [comment] 2022-10-24 01:08
Thank you for responding.  I will attempt to answer all your questions to the best of my ability. 

I have 5 different websites I monitor (some on different hosting).  

I am using default settings in the Webmon app. 

I prefer not to share the websites at this time, as some are personal, and some are work for hire. 

"Does it always happen the same way or does it vary?":  
I do not really understand this question fully, but I will attempt to address it.  Sometimes I get notifications when I am not actively looking at the phone (and in this case I have always assumed the websites had an issue but resumed working before I could check); however at other times I am using the phone when the notification pops up saying one, some, or all of the websites were unreachable, and at that moment I click the notification instantly and the app opens and shows all websites working correctly, and checking the websites manually from multiple devices shows they are also all working correctly. 

If I have answered anything not to your satisfaction, please clarify and I will attempt to provide better information if I am able to. 

Thank you again for your time to address this issue report.

**Comment by theAkito** [comment] 2022-10-24 01:44
> I do not really understand this question fully, but I will attempt to address it. Sometimes I get notifications when I am not actively looking at the phone (and in this case I have always assumed the websites had an issue but resumed working before I could check); however at other times I am using the phone when the notification pops up saying one, some, or all of the websites were unreachable, and at that moment I click the notification instantly and the app opens and shows all websites working correctly, and checking the websites manually from multiple devices shows they are also all working correctly.

Interesting. This helps a lot.

Could you turn on the feature, which ignores failure due to a missing internet connection, rather than the website being down?
Once you turn that on, keep the phone running as before and try to see, if the faulty notifications stop appearing, if possible to notice.

Was "saying one, some, or all of the websites were unreachable" just an example or does it vary?
Are most of the time all addresses unreachable?

>shows all websites working correctly, and checking the websites manually from multiple devices shows they are also all working correctly.

Does that mean you issue a manual refresh or just look at the list of websites?

____

It would also help, if you provided more information about your phone.

Do you use a custom ROM? The default one?
Either way, it would help if you posted information about the OS.

Do you have power saving apps installed?

____

As a side note:

https://dontkillmyapp.com/

The app seems to be running in the background, since you are retrieving notifications, though I still want to point out that stock Samsung phones are extremely aggressive in regards to "power saving".
They kill even very important system apps, etc.

It wouldn't surprise me at all, if there were internet connection issues on a stock Samsung phone.

**Comment by Git-Forked** [comment] 2022-10-24 02:33
"Could you turn on the feature, which ignores failure due to a missing internet connection, rather than the website being down?
Once you turn that on, keep the phone running as before and try to see, if the faulty notifications stop appearing, if possible to notice."

Okay, I will try that and let you know the results. 

"Was "saying one, some, or all of the websites were unreachable" just an example or does it vary?
Are most of the time all addresses unreachable?"

That part does vary. 

"Does that mean you issue a manual refresh or just look at the list of websites?"

Either shows the same result of all websites up.

"Are some of them on a development server, which has low performance?
Does it take long to load those websites on the other devices?"

None are on development servers.  They are on GoDaddy hosting, and DirectNic hosting.

"Do you use a custom ROM? The default one?"

I use stock rom that came with the phone. 

"Either way, it would help if you posted information about the OS."

Model:  SM-S111DL
Hardware Version:  Rev3.0
One UI Core 2.0
Android Version 10
Baseband Version: S111DLUDU5AUD1
Kernel Version:  4.9.186-21441264

"Do you have power saving apps installed?"

Webmon is added to the "Apps that won't be put to sleep" list.

**Comment by theAkito** [comment] 2022-10-24 02:50
> I use stock rom that came with the phone.

Seems like this might be an issue.

Still, I'll check it out and will try to reproduce the issue in various ways.

I'll get back to this issue, when I get results.

**Comment by theAkito** [comment] 2022-12-15 04:32
> "Could you turn on the feature, which ignores failure due to a missing internet connection, rather than the website being down? Once you turn that on, keep the phone running as before and try to see, if the faulty notifications stop appearing, if possible to notice."
> 
> Okay, I will try that and let you know the results.

How did that go?

**Comment by Git-Forked** [comment] 2022-12-16 18:35
I haven't had any notifications at all since changing settings, even when the websites are down.

**Comment by theAkito** [comment] 2022-12-16 21:39
> I haven't had any notifications at all since changing settings, even when the websites are down.

If that is the case, that means that the problem was always related to bad internet connectivity on your phone. Once you disable the feature, which ignores errors due to internet connectivity, the notifications should appear again, because your phone has issues staying connected with the internet.

**Comment by theAkito** [comment] 2022-12-20 02:51
@Git-Forked

Did you receive notifications again, after disabling the feature?

**Comment by theAkito** [comment] 2022-12-27 12:20
No feedback & cannot reproduce.

**Comment by theAkito** [comment] 2022-12-27 12:20
No feedback & cannot reproduce.

**Closed by theAkito** 2022-12-27 12:20 UTC
Labels: awaiting-response
