### ISSUE TITLE
Floating action button obstructs service entry options button

### ISSUE THREAD

**Issue by Tha14** [theAkito/webmon#24] opened 2021-11-26 00:53 UTC
#### Required Information
Project version
v2.6.0

#### Steps to reproduce

Add enought services to monitor until the list is filled to bottom of the view.

#### Expected behaviour

The button for the options of the service at the bottom of the screen should be visible and tappable.

#### Actual behaviour

The button for the service options at the bottom is getting obstructed by the floating action button.

#### Extra details

![Screenshot_20211126-024645358 (1)](https://user-images.githubusercontent.com/5931740/143511565-1bc396d6-055b-41bd-8e16-88ca9628a92c.jpg)

**Comment by theAkito** [comment] 2021-11-26 00:58
Greetings, @Tha14. 👋🏻


Your issue is extremely weird. The Floating Action Button always auto-hides when I scroll down. Tested it on Android 5, 8, 10, 11 emulators, plus Android 11 on my real phone.

Does the button never hide, even if you scroll down completely?

**Comment by Tha14** [comment] 2021-11-27 16:47
@theAkito Hey, no, the button does not go away because there are no more contents to allow for scroll to work. Maybe this can be fixed with a scroll gesture detection(not sure on the name of this) so that the button always hides when you scroll up? It's not a big problem since I can add more services to monitor and it starts working properly, I just felt you should know about this minor issue. :)

**Comment by theAkito** [comment] 2021-11-27 16:53
@Tha14 Oh! I understand now. Actually, you hit a type of edge case, of which I thought, nobody would notice, anyway. 😆

Here is a similar issue I noticed:
https://github.com/theAkito/webmon/issues/17

It's about the Floating Action Button disappearing forever (or until app restart), after deleting a WebsiteEntry, when you have a specific amount on the screen. It is related to the same core issue, this issue is rooted from.



> I just felt you should know about this minor issue. :)

Indeed, thank you for the message. 🙂 I want to make the app very user friendly and perhaps even beginner friendly. So, such minor issue is of importance for me, too.

Since we have two FAB issues now and I'm not the only one noticing them, I'm putting these two issues on my plan for the next release.

Thank you! 😃

**Comment by theAkito** [comment] 2021-12-01 02:14
@Tha14

I currently am trying to reproduce the issue, but the button always hides, even if web services are only filled to the bottom of the screen. Could you tell me your phone specs, so I can try an emulator with the same pixels as your phone has?

**Comment by Tha14** [comment] 2021-12-01 09:37
@theAkito 
Hope this helps:
```
Drawable density: hdpi
Layout size: large
Screen (dpi): 240
Width (px): 720
Height (px): 1280
Usable width (px): 720
Usable height (px): 1280
Width (dp): 480
Height (dp): 853
Smallest dp: 480
Orientation: Portrait
Orientation degree: 0°
Diagonal Size(inches): 5.0
X dpi: 295.0
Y dpi: 295.6
Touchscreen: Finger
Refresh rate (fps): 60.0

**Comment by theAkito** [comment] 2021-12-01 16:22
@Tha14

I see, that I already tested with precisely the same pixel amounts (720 x 1280) and I still don't see that issue happening. It could be related to the other resolution related specs, but I'm not sure. The biggest difference I see is that using a 720 x 1280 screen only allows me to see 4 website entries. Opposed to that, you can see 6 at once. I cannot explain how the difference is so big, when we are using the same amount of pixels.

Could you please tell me your phone's complete specs? Including phone model, etc. Thank you. 🙂

**Comment by Tha14** [comment] 2021-12-01 16:51
@theAkito Did you change the dpi to 240? That's probably why it's hard to reproduce.

**Comment by theAkito** [comment] 2021-12-01 21:21
@Tha14

I tried all possible dpi values between 160 and 280. It never fits in the way that is seen on your screenshot.

Could you please tell me your phone's complete specs?

If your device is so exceptional, I would most likely just implement this fix for this specific device, as I can't reproduce it on any other device configuration that I have tried, including ones with different pixel by pixel ratios, etc.

**Comment by Tha14** [comment] 2021-12-01 21:28
@theAkito As you said, it's an edge case and I have custom values for the device I am using. It's a Xiaomi Redmi 4x if it helps. If you have more important matters to attend to then this can wait :)

**Comment by theAkito** [comment] 2021-12-01 21:31
> It's a Xiaomi Redmi 4x if it helps.

Yes, that helps, thank you.



> I have custom values for the device I am using.

Does that mean a generic Redmi 4x wouldn't display this behaviour?

If this problem arises from your customisation, I would probably implement an advanced feature, that allows the user to decide for themselves if they want to activate such fix.

**Comment by Tha14** [comment] 2021-12-01 21:37
No, I don't think it would since it comes with a different DPI setting out of the box but I can't say it won't happen to other devices.  And yeah, if you can add an option in the settings it would be best.

**Closed** 2021-12-02 16:55 UTC
Labels: bug

**Comment by theAkito** [comment] 2021-12-02 16:58
Initially, I attempted to implement a fancy feature to fix this issue, however in the process of doing that I discovered that it would take a lot of work for such a simple thing to happen. Therefore, I decided to implement a simple and quick, but effective fix.

You can now hide the Floating Action Button and have an "Add Entry" menu item in the main menu (three dots in the top right corner of the app's home), instead. It's not the most beautiful solution, but it works for now. I will probably make it more user friendly in the future.

Hope this fix helps. 🙂
